### ISSUE TITLE
More than one theme selected

### ISSUE THREAD

**Issue by tsdye** [alezost/emacs-utils#1]
Aloha Alex,
When I use utl-load-theme to change from solarized to alect-dark, Emacs thinks I want to select more than one theme at a time.  Also, as you'll see in the attached image, selecting these two themes at once spoils the beauty of alect-dark.

I'm using Emacs 24.5 on a Mac.  I install and upgrade Emacs with MacPorts, in case that makes a difference.
I like the convenience of utl-load-theme and would like to use it successfully.

All the best,
Tom

![two-selected](https://cloud.githubusercontent.com/assets/125573/9560536/07fb9820-4db5-11e5-9d82-afe4849d0789.png)

**Comment by alezost** [comment]
(Ouch, I didn't thought that someone else uses anything from this repo)

Hello, Tom!

You may skip the next paragraph, as I have just fixed this issue,
so `utl-load-theme` should work as expected now.

I think what you described happened because initially "solarized"
was loaded with `load-theme` function, so `utl-load-theme` didn't
know what theme was used, as it "remembers" only a theme it
loads.  But it is not the case anymore, since now
`utl-load-theme` unloads all enabled themes before loading the
specified one.

Thank you for reporting!

**Comment by tsdye** [comment]
Aloha Alex,

Alex Kost notifications@github.com writes:

> (Ouch, I didn't thought that someone else uses anything from this repo)
> 
> Hello, Tom!
> 
> You may skip the next paragraph, as I have just fixed this issue,
> so `utl-load-theme` should work as expected now.
> 
> I think what you described happened because initially "solarized"
> was loaded with `load-theme` function, so `utl-load-theme` didn't
> know what theme was used, as it "remembers" only a theme it
> loads.  But it is not the case anymore, since now
> `utl-load-theme` unloads all enabled themes before loading the
> specified one.

Yes, that sounds right.  It didn't fail on subsequent loads.

Now it works correctly right from the start.

Thanks,
Tom

## 

Thomas S. Dye
http://www.tsdye.com
